print("[Bernie] Tuning-Module is loading...")

local GLOBAL = GLOBAL or _G

TUNING.WES_WORK_MULTIPLIER = 1

TUNING.OCEANTREE_STAGES_TO_SUPERTALL = 2
TUNING.OCEANTREE_ENRICHED_COOLDOWN_MIN = 400
TUNING.OCEANTREE_ENRICHED_COOLDOWN_VARIANCE = 120

TUNING.BEEFALO_HUNGER_RATE = TUNING.BEEFALO_HUNGER_RATE * 0.9
TUNING.BEEFALO_DOMESTICATION_ATTACKED_BY_PLAYER_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_ATTACKED_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_LOSE_DOMESTICATION = 0
TUNING.BEEFALO_DOMESTICATION_ATTACKED_OBEDIENCE = 0
TUNING.BEEFALO_DOMESTICATION_GAIN_DOMESTICATION = TUNING.BEEFALO_DOMESTICATION_GAIN_DOMESTICATION * 1.1
TUNING.BEEFALO_DOMESTICATION_BRUSHED_DOMESTICATION = TUNING.BEEFALO_DOMESTICATION_BRUSHED_DOMESTICATION * 1.1

TUNING.HEATROCK_NUMUSES = TUNING.HEATROCK_NUMUSES * 3
TUNING.RUINS_BAT_DAMAGE = TUNING.RUINS_BAT_DAMAGE * 1.1

TUNING.BUILD_DISTANCE = 0.9

print("[Bernie] Tuning-Module loaded!")
